spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scp
    username: RAAxFWVjeEz
    password: QyTAbRwWyVZtGDBp4Hoq
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
      ddl-auto: none
    show-sql: true    # 打印数据库语句
  flyway:
    locations: classpath:db/migration
    table: flyway_schema_history
  sql:
    init:
      mode: always

  data:
    redis:
      jedis:
        pool:
          enabled: false
      host: 127.0.0.1
      port: 6379
      password: scp@redis?pass