#!/bin/sh -e

cd "$(dirname "$0")/.."

nerdctl compose --file local/docker/docker-compose-dev.yml down -v

. ./local/set-env-vars

OLD_IMAGE_ID=$(nerdctl images -q "${REPOSITORY}" | uniq)

if [ "$OLD_IMAGE_ID" != "" ]; then
    echo "$OLD_IMAGE_ID" | xargs nerdctl rmi
fi


nerdctl build -t "${DOCKER_IMAGE}" .
