apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jnlp-slave
  name: jnlp-slave
spec:
  serviceAccount: jenkins-agent
  containers:
  - name: kaniko-crane
    image: weijilab/kaniko-crane
    tty: true
    command:
    - cat
  - name: argocd-auto-sync
    image: 729601114034.dkr.ecr.ap-northeast-1.amazonaws.com/argocd-auto-sync
    tty: true
    command:
    - cat
  - name: trivy
    image: aquasec/trivy
    entrypoint: ""
    tty: true
    command:
    - cat
  - name: jnlp
    image: "729601114034.dkr.ecr.ap-northeast-1.amazonaws.com/jnlp-slave-docker:latest"
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
  - name: "dind"
    image: "docker:20.10.3-dind"
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    securityContext:
      privileged: true
