spring:
  application:
    name: scp-api
  profiles:
    active: local
  flyway:
    locations: classpath:db/migration
    table: flyway_schema_history

server:
  port: 8081

jwt:
  secret: ${jwt.secret.string}

saml:
  cer-path: ${saml.cer.path}

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: security check platform
  try-host: http://localhost:${server.port}
