#!/bin/bash -e

cd $(dirname $0)/..
source ./scripts/set-env-vars

echo "Check repo ${APP_NAME}"

aws ecr describe-repositories \
  --repository-names $APP_NAME \
  --region $AWS_REGION > /dev/null >&1 || \
aws ecr create-repository \
  --repository-name $APP_NAME \
  --region $AWS_REGION
